apiVersion: apps/v1
kind: Deployment
metadata:
  name: owkew
spec:
  replicas: 1
  selector:
    matchLabels:
      app: owkew
  template:
    metadata:
      labels:
        app: owkew
    spec:
      containers:
      - image: okteto.dev/owkew:latest
        name: owkew
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/L-html.zip"
        - name: Vless_UUID
          value: "5d7e9469-c8e5-4e6a-a8f5-442233dc7c6b"
        - name: Vless_Path
          value: "/5d7e9469-c8e5-4e6a-a8f5-442233dc7c6b-vless"
        - name: Vmess_UUID
          value: "5d7e9469-c8e5-4e6a-a8f5-442233dc7c6b"
        - name: Vmess_Path
          value: "/5d7e9469-c8e5-4e6a-a8f5-442233dc7c6b-vmess"
        - name: Share_Path
          value: "/ererenk"
